name: Build docker image and push into dockerhub

on: # specify the build to trigger the automated ci/cd
    push:
        branches:
            - "main"

jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest # specify the build machine
        steps:
            - # checkout to the repository on the build machine
                name: Checkout
                uses: actions/checkout@v3
            - # login to Docker Hub using the secrets provided
                name: Docker login
                env:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PROVIDERTOKEN }}
                run: docker login -u $username -p $password
            - # create the image
                name: Build image
                run: docker build . --file base_OpenJDK8/Dockerfile --tag deepyad76/openjdk8:latest 
            - # build the container image and push it to Docker Hub 
                name: Push image
                run: docker push deepyad76/openjdk8:latest
